export const STORAGE_KEYS =
{
  ACCESS_TOKEN: "KEY_ACCESS_TOKEN",
  REFRESH_TOKEN: "KEY_REFRESH_TOKEN",
  ID_SESSION: "KEY_ID_SESSION",
  ADMIN_USER_INFO: "KEY_ADMIN_USER_INFO",
  DEVICE_ADDRESS: "KEY_DEVICE_ADDRESS",
  ID_DEVICE: "KEY_ID_DEVICE",
} as const;
